// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAGGmq1idUNDiB_URb-ge16_fTqDjuKQE',
    appId: '1:60076541898:android:b716b3fd968875e444b133',
    messagingSenderId: '60076541898',
    projectId: 'wordle-130b8',
    storageBucket: 'wordle-130b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqzD8rd5pt4i5DBqm-aIWAizRG12kdKCU',
    appId: '1:60076541898:ios:ae54371990bcbf3044b133',
    messagingSenderId: '60076541898',
    projectId: 'wordle-130b8',
    storageBucket: 'wordle-130b8.appspot.com',
    iosClientId: '60076541898-o0tevm2dplbbqoit4jfd3m1d3co2t3q5.apps.googleusercontent.com',
    iosBundleId: 'com.ngwz.wordle',
  );
}
